### ISSUE TITLE
Missing env var causes error.

### ISSUE THREAD

**Issue by Restless-ET** [byrnedo/docker-nginx-php7-fpm#1]
When running a container based on your image I was getting the following error:

`/cmd.sh: line 8: ERRORS: unbound variable`

I believe this was due to fact the such variable isn't defined anywhere (nor any mention for it is made on the docs), so I think that at least a note on the README could be added. :)

**Comment by Restless-ET** [comment]
I see you've already applied a fix and added a note on the README so I'll close this issue.

**Comment by byrnedo** [comment]
Hahah, you're on top of things! 

Thanks for flagging that, I use these myself but the docs aren't usually too good.
